steps:
  # Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/immig4u/my-repo/hello:$COMMIT_SHA', '.']
    id: BUILD

  # Storage of the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/immig4u/my-repo/hello:$COMMIT_SHA']
    id: STORAGE

  # Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'hello-site',
          '--image', 'us-central1-docker.pkg.dev/immig4u/my-repo/hello:$COMMIT_SHA',
          '--region', 'us-central1',
          '--platform', 'managed',
          '--no-traffic',
          '--allow-unauthenticated']
    id: DEPLOY

  # Canary
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'update-traffic', 'hello-site',
          '--region', 'us-central1',
          '--to-revisions=LATEST=50']
    id: CANARY

# Add this section to specify the logs bucket
options:
  logging: GCS_ONLY
  logsBucket: 'gs://immigration-app'

# If you're using a custom service account, specify it here
serviceAccount: 'projects/immig4u/serviceAccounts/ryu-201@immig4u.iam.gserviceaccount.com'
