steps:

  # Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/nusantaraai/my-repo/hello:$COMMIT_SHA', '.']
    id: BUILD

  # Storage of the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast2-docker.pkg.dev/nusantaraai/my-repo/hello:$COMMIT_SHA']
    id: STORAGE

  # Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'hello-site',
          '--image', 'northamerica-northeast2-docker.pkg.dev/nusantaraai/my-repo/hello:$COMMIT_SHA',
          '--region', 'northamerica-northeast2',
          '--platform', 'managed',
          '--no-traffic',
          '--allow-unauthenticated']
    id: DEPLOY

  # Canary
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'update-traffic', 'hello-site',
          '--region', 'northamerica-northeast2',
          '--to-revisions=LATEST=50']
    id: CANARY
